spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # execute data.sql
    defer-datasource-initialization: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
      setting:
        web-allow-others: true
      path: /h2-console